apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: synergist-bq-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bqapi
    spec:
      containers:
      - name: bqapi
        image: gcr.io/synergist-170903/synergist_bigquery_api:dev
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/bq/bq.json
        ports:
        - containerPort: 8080
        volumeMounts: 
        - name: bq-secret
          mountPath: "/etc/bq"
          readOnly: true
      volumes:
      - name: bq-secret
        secret:
          secretName: synergist-dev-key
