version: '2'
services:
  angular:
    image: umasskapelletier/synergist_client:latest
    ports:
      - "80:80"
    links:
      - webapi
  webapi:
    image: umasskapelletier/synergist_webapi:latest
    expose:
      - "5000"
    depends_on:
     - neo4j
  neo4j:
      image: neo4j:latest
      ports:
        - "7474:7474"
        - "7687:7687"
        - "7473:7473"
      volumes:
      - /mnt/disks/neo4j/data:/var/lib/neo4j/data
      - /mnt/disks/neo4j/logs:/var/lib/neo4j/logs
      - /mnt/disks/neo4j/conf:/var/lib/neo4j/conf
