apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: synergist-webapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: docker.io/umasskapelletier/synergist_webapi:latest
        ports:
        - containerPort: 5000
